django_tareas/urls.py
from django.urls import path
from . import views

app_name = 'django_tareas'

urlpatterns = [
    path('', views.index,name='index'),
    path('consolaAdministrador',views.consolaAdministrador,name='consolaAdministrador'),
    path('cerrarSesion',views.cerrarSesion,name='cerrarSesion'),
    path('eliminarUsuario/<str:ind>',views.eliminarUsuario,name='eliminarUsuario'),
    path('verUsuario/<str:ind>',views.verUsuario, name='verUsuario'),
    path('nuevaTarea/<str:ind>', views.nuevaTarea, name='nuevaTarea'),
    path('devolverMensaje', views.devolverMensaje, name='devolverMensaje'),
    path('conseguirInfoTarea',views.conseguirInfoTarea,name='conseguirInfoTarea'),
    path('eliminarTarea/<str:idTarea>&<str:idUsuario>',views.eliminarTarea,name='eliminarTarea'),
    path('descargarTareas/<str:idUsuario>',views.descargarTareas,name='descargarTareas'),
    path('react', views.react, name='react'),
    path('iterarReact',views.iterarReact,name='iterarReact'),
    path('publicarComentario',views.publicarComentario,name='publicarComentario'),
    path('descargarReporteUsuarios',views.descargarReporteUsuarios,name='descargarReporteUsuarios'),
    path('devolverInfoUsuario',views.devolverInfoUsuario,name='devolverInfoUsuario'),
    path('conseguirInfoUsuario',views.conseguirInfoUsuario,name='conseguirInfoUsuario'),
    path('modificarUsuario',views.modificarUsuario,name='modificarUsuario')
]

proyectoTareas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django_tareas.urls'))
]

django_tareas/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
# Create your models here.

class datosUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tipoUsuario = models.CharField(max_length=32,default='USUARIO')
    nroCelular = models.CharField(max_length=32, default='999888777')
    profesionUsuario = models.CharField(max_length=32, default='DEVELOPER')
    perfilUsuario = models.CharField(max_length=512, default='')
    fechaIngreso = models.DateField(default=date.today)

class tareasInformacion(models.Model):
    usuarioRelacionado = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcionTarea = models.CharField(max_length=512, default='')
    fechaInicio = models.DateField(default=date.today)
    fechaFin = models.DateField(default=date.today)
    estadoTarea = models.CharField(max_length=32,default='PROCESO')

class comentarioTarea(models.Model):
    tareaRelacionada = models.ForeignKey(tareasInformacion, on_delete=models.CASCADE)
    usuarioRelacionado = models.ForeignKey(User, on_delete=models.CASCADE)
    comentarioTarea = models.CharField(max_length=512, default='')

django_tareas/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, JsonResponse, FileResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import datosUsuario, tareasInformacion, comentarioTarea
import datetime
import json
from django.db.models import Count

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4

# Create your views here.
def index(request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        contraUsuario = request.POST.get('contraUsuario')
        usuarioInfo = authenticate(request,username=nombreUsuario,password=contraUsuario)
        if usuarioInfo is not None:
            login(request,usuarioInfo)
            if usuarioInfo.datosusuario.tipoUsuario == 'ADMINISTRADOR':
                return HttpResponseRedirect(reverse('django_tareas:consolaAdministrador'))
            else:
                return HttpResponseRedirect(reverse('django_tareas:verUsuario', kwargs={'ind':usuarioInfo.id}))
        else:
            return HttpResponseRedirect(reverse('django_tareas:index'))
    return render(request,'ingresoUsuario.html')

@login_required(login_url='/')
def cerrarSesion(request):
    logout(request)
    return HttpResponseRedirect(reverse('django_tareas:index'))

@login_required(login_url='/')
def consolaAdministrador(request):
    if request.user.datosusuario.tipoUsuario == 'ADMINISTRADOR':
        if request.method == 'POST':
            usernameUsuario = request.POST.get('usernameUsuario')
            contraUsuario = request.POST.get('contraUsuario')
            nombreUsuario = request.POST.get('nombreUsuario')
            apellidoUsuario = request.POST.get('apellidoUsuario')
            tipoUsuario = request.POST.get('tipoUsuario')
            nroCelular = request.POST.get('nroCelular')
            profesionUsuario = request.POST.get('profesionUsuario')
            perfilUsuario = request.POST.get('perfilUsuario')
            emailUsuario = request.POST.get('emailUsuario')
            usuarioNuevo = User.objects.create(
                username=usernameUsuario,
                email=emailUsuario,
            )
            usuarioNuevo.set_password(contraUsuario)
            usuarioNuevo.first_name = nombreUsuario
            usuarioNuevo.last_name = apellidoUsuario
            usuarioNuevo.is_staff = True
            usuarioNuevo.save()
            datosUsuario.objects.create(
                user=usuarioNuevo,
                tipoUsuario = tipoUsuario,
                nroCelular = nroCelular,
                profesionUsuario=profesionUsuario,
                perfilUsuario = perfilUsuario
            )
            return HttpResponseRedirect(reverse('django_tareas:consolaAdministrador'))
        return render(request,'consolaAdministrador.html',{
            'usuariosTotales':User.objects.all().order_by('id')
        })
    else:
        return HttpResponseRedirect(reverse('django_tareas:verUsuario', kwargs={'ind':request.user.id}))

def eliminarUsuario(request,ind):
    usuarioEliminar = User.objects.get(id=ind)
    datosUsuario.objects.get(user=usuarioEliminar).delete()
    usuarioEliminar.delete()
    return HttpResponseRedirect(reverse('django_tareas:consolaAdministrador'))

@login_required(login_url='/')
def verUsuario(request, ind):
    usuarioInformacion = User.objects.get(id=ind)
    tareasUsuario = tareasInformacion.objects.filter(usuarioRelacionado=usuarioInformacion).order_by('id')
    return render(request,'informacionUsuario.html',{
        'usuarioInfo': usuarioInformacion,
        'tareasUsuario': tareasUsuario
    })

def nuevaTarea(request, ind):
    if request.method == 'POST':
        usuarioRelacionado = User.objects.get(id=ind)
        fechaInicio = request.POST.get('fechaInicio')
        fechaFin = request.POST.get('fechaFin')
        descripcionTarea = request.POST.get('descripcionTarea')
        fechaSeparada = fechaInicio.split('-')
        ini_dia = int(fechaSeparada[2])
        ini_mes = int(fechaSeparada[1])
        ini_anho = int(fechaSeparada[0])
        fechaSeparada = fechaFin.split('-')
        fin_dia = int(fechaSeparada[2])
        fin_mes = int(fechaSeparada[1])
        fin_anho = int(fechaSeparada[0])
        fechaInicioRegistro = datetime.datetime(ini_anho, ini_mes, ini_dia)
        fechaFinRegistro = datetime.datetime(fin_anho, fin_mes, fin_dia)
        tareasInformacion.objects.create(
            fechaInicio=fechaInicioRegistro,
            fechaFin=fechaFinRegistro,
            descripcionTarea=descripcionTarea,
            usuarioRelacionado=usuarioRelacionado,
        )
        return HttpResponseRedirect(reverse('django_tareas:verUsuario', kwargs={'ind':ind}))

def devolverMensaje(request):
    print(request.GET)
    nombre = request.GET.get('nombre')
    apellido = request.GET.get('apellido')
    edad = request.GET.get('edad')
    profesion = request.GET.get('profesion')
    print(nombre)
    print(apellido)
    print(edad)
    print(profesion)
    return JsonResponse({
        "nombre":nombre,
        "edad":edad,
        "apellido":apellido,
        "profesion":profesion,
        "funcion":"devolverMensaje",
        "fechaEjecuacion":"2023-04-14",
    })

def devolverInfoUsuario(request):
    nombre=request.GET.get('nombre')
    apellido=request.GET.get('apellido')
    idUsuario=request.GET.get('idUsuario')
    return JsonResponse({
        'nombre':nombre,
        'apellido':apellido,
        'idUsuario':idUsuario
    })

def conseguirInfoUsuario(request):
    idUsuario= request.GET.get('idUsuario')
    usuarioSeleccionado=User.objects.get(id=idUsuario)
    return JsonResponse({
        'nombreUsuario': usuarioSeleccionado.first_name,
        'apellidoUsuario':usuarioSeleccionado.last_name,
        'emailUsuario':usuarioSeleccionado.email,
        'fechaIngreso':usuarioSeleccionado.datosusuario.fechaIngreso.strftime("%d-%m-%Y"),
        'celular':usuarioSeleccionado.datosusuario.nroCelular,
        'profesionUsuario':usuarioSeleccionado.datosusuario.profesionUsuario,
        'idUsuario':idUsuario

    })

def conseguirInfoTarea(request):
    comentariosTotales = []
    idTarea = request.GET.get('idTarea')
    tareaSeleccionada = tareasInformacion.objects.get(id=idTarea)
    comentariosTarea = tareaSeleccionada.comentariotarea_set.all()
    for comentario in comentariosTarea:
        comentariosTotales.append([str(comentario.usuarioRelacionado.first_name + ' ' + comentario.usuarioRelacionado.last_name),comentario.comentarioTarea])
    print(comentariosTotales)
    return JsonResponse({
        'descripcionTarea':tareaSeleccionada.descripcionTarea,
        'estadoTarea':tareaSeleccionada.estadoTarea,
        'fechaInicio':tareaSeleccionada.fechaInicio.strftime("%d-%m-%Y"),
        'fechaFin':tareaSeleccionada.fechaFin.strftime("%d-%m-%Y"),
        'idTarea':str(tareaSeleccionada.id),
        'comentariosTotales':comentariosTotales,
    })

def modificarUsuario(request):
    datos=json.load(request)
    cargaId= datos.get('idUsuario')
    print(cargaId)
    nroCelular=datos.get('nroCelular')
    profesionUsuario=datos.get('profesionUsuario')
    usuarioModificado=datosUsuario.objects.get(id=cargaId)
    usuarioModificado.nroCelular=nroCelular
    usuarioModificado.profesionUsuario=profesionUsuario
    usuarioModificado.save()
    return JsonResponse({
        'respuesta':'actualizado' 
    })
    


def eliminarTarea(request,idTarea,idUsuario):
    tareasInformacion.objects.get(id=idTarea).delete()
    return HttpResponseRedirect(reverse('django_tareas:verUsuario', kwargs={'ind':idUsuario}))

def descargarTareas(request,idUsuario):
    usuarioInformacion = User.objects.get(id=idUsuario)
    tareasUsuario = tareasInformacion.objects.filter(usuarioRelacionado=usuarioInformacion).order_by('id')
    nombreArchivo = 'tareas-' + f'{usuarioInformacion.username}' + '.pdf'

    archivoPdf = canvas.Canvas(nombreArchivo,A4)

    archivoPdf.drawImage('./django_tareas/static/logoApp.png',20, 700, width=140, height=80)
    archivoPdf.drawImage('./django_tareas/static/logoPUCP.png',430, 700, width=140, height=80)
    
    archivoPdf.setFont('Helvetica-Bold',25)
    archivoPdf.drawCentredString(297.5,730,'Reporte de tareas')

    #Informacion del usuario
    archivoPdf.setFont('Helvetica-Bold',12)
    archivoPdf.drawString(40,620, 'Nombre de usuario')
    archivoPdf.drawString(40,605, 'Primer nombre')
    archivoPdf.drawString(40,590, 'Apellido')
    archivoPdf.drawString(40,575, 'Email')

    archivoPdf.drawString(155,620, ':')
    archivoPdf.drawString(155,605, ':')
    archivoPdf.drawString(155,590, ':')
    archivoPdf.drawString(155,575, ':')

    archivoPdf.setFont('Helvetica',12)
    archivoPdf.drawString(160,620, f'{usuarioInformacion.username}')
    archivoPdf.drawString(160,605, f'{usuarioInformacion.first_name}')
    archivoPdf.drawString(160,590, f'{usuarioInformacion.last_name}')
    archivoPdf.drawString(160,575, f'{usuarioInformacion.email}')

    archivoPdf.setFont('Helvetica-Bold',12)
    archivoPdf.drawString(300,620, 'Tipo de usuario')
    archivoPdf.drawString(300,605, 'Profesion del usuario')
    archivoPdf.drawString(300,590, 'Nro de celular')
    archivoPdf.drawString(300,575, 'Fecha de ingreso')

    archivoPdf.drawString(425,620, ':')
    archivoPdf.drawString(425,605, ':')
    archivoPdf.drawString(425,590, ':')
    archivoPdf.drawString(425,575, ':')

    archivoPdf.setFont('Helvetica',12)
    archivoPdf.drawString(430,620, f'{usuarioInformacion.datosusuario.tipoUsuario}')
    archivoPdf.drawString(430,605, f'{usuarioInformacion.datosusuario.profesionUsuario}')
    archivoPdf.drawString(430,590, f'{usuarioInformacion.datosusuario.nroCelular}')
    archivoPdf.drawString(430,575, f'{usuarioInformacion.datosusuario.fechaIngreso.strftime("%d-%m-%Y")}')

    lista_x = [40,550]

django_tareas/templates/informacionUsuario.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Vista de ingreso</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <!--Importar scripts de javascript-->
        <script src="{% static 'informacionUsuario.js' %}"></script>
    </head>
    <body>
        <div class="bg-primary">
            <div class="container">
                <div class="row justify-content-between align-items-center">
                    <div class="col-4 mt-3 mb-3 text-white">
                        <div class="row">
                            <h5>Bienvenido {{ user.first_name }} {{ user.last_name }}</h5>
                        </div>
                        <div class="row">
                            <h5>{{ user.datosusuario.profesionUsuario }}</h5>
                        </div>
                    </div>
                    <div class="col-1">
                        <a class="btn btn-success" href="{% url 'django_tareas:cerrarSesion' %}"><i class="fa-solid fa-right-to-bracket"></i> Salir</a>
                    </div>
                </div>
            </div>
        </div>
        {% if user.datosusuario.tipoUsuario == 'ADMINISTRADOR' %}
        <div class="container mt-3 mb-3">
            <div>
                <a href="{% url 'django_tareas:consolaAdministrador' %}" class="btn btn-info"><i class="fa-solid fa-arrow-left"></i></a>
            </div>
        </div>
        {% endif %}
        <div class="mt-5 text-center mb-3">
            <h1>Informacion del usuario : {{ usuarioInfo.first_name }} {{ usuarioInfo.last_name }}</h1>
        </div>
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-5 bg-light" style="border-radius: 20px;">
                    <div class="row mb-2 mt-2">
                        <div class="col-5">
                            <h5>Nombre completo : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ usuarioInfo.first_name }} {{ usuarioInfo.last_name }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Nombre de usuario : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ usuarioInfo.username }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Email : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ usuarioInfo.email }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Profesion del usuario : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ usuarioInfo.datosusuario.profesionUsuario }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Nro de celular : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ usuarioInfo.datosusuario.nroCelular }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Tipo de usuario : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ usuarioInfo.datosusuario.tipoUsuario }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Fecha de registro : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ usuarioInfo.datosusuario.fechaIngreso|date:"Y-m-d" }}</i>
                        </div>
                    </div>
                </div>
                <div class="col-5 bg-light h-100" style="border-radius: 20px;">
                    <div class="row mb-2 mt-2">
                        <div class="col-5">
                            <h5>Perfil : </h5>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-12">
                            <i>{{ usuarioInfo.datosusuario.perfilUsuario }}</i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-5 text-center mb-3">
            <h3>Tareas del usuario</h3>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2 text-start">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevaTarea"><i class="fa-solid fa-calendar-plus"></i> Nueva tarea</button>
                </div>
                <div class="col-2 text-end">
                    <a class="btn btn-success" href="{% url 'django_tareas:descargarTareas' usuarioInfo.id %}"><i class="fa-solid fa-download"></i> Descargar</a>
                </div>
            </div>
        </div>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <th>Fecha de inicio</th>
                            <th>Fecha de finalizacion</th>
                            <th>Estado de la tarea</th>
                            <th>Ver tarea</th>
                            <th>Finalizar</th>
                            <th>Eliminar</th>
                        </thead>
                        <tbody>
                            {% for tarea in tareasUsuario %}
                            <tr>
                                <td>{{ tarea.fechaInicio|date:'d-m-Y' }}</td>
                                <td>{{ tarea.fechaFin|date:'d-m-Y' }}</td>
                                <td id="estado{{ tarea.id }}">{{ tarea.estadoTarea }}</td>
                                <td><button data-bs-toggle="modal" data-bs-target="#detalleTarea" id="{{ tarea.id }}" class="btn btn-info" onclick="capturarInformacionTarea(this.id)"><i class="fa-solid fa-eye"></i></button></td>
                                <td><button class="btn btn-warning" id="finalizar{{ tarea.id }}" onclick="finalizarTarea(this.id)"><i class="fa-solid fa-forward-step"></i></button></td>
                                <td><a class="btn btn-danger" href="{% url 'django_tareas:eliminarTarea' tarea.id usuarioInfo.id %}"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

<!--Nueva tarea-->
<div class="modal fade" id="nuevaTarea" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'django_tareas:nuevaTarea' usuarioInfo.id %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Crear nueva tarea</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Fecha de inicio</label>
                            <input class="form-control" type="date" required name="fechaInicio">
                        </div>
                        <div class="col-5">
                            <label>Fecha de finalizacion</label>
                            <input class="form-control" type="date" required name="fechaFin">
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-11">
                            <label>Descripcion de la tarea</label>
                            <textarea class="form-control" type="text" required rows="4" name="descripcionTarea"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!--Detalle tarea-->
<div class="modal fade" id="detalleTarea" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detalle de la tarea</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" onclick="eliminarInfo()" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h1 style="display: none;" id="indTarea"></h1>
                <div class="row form-group justify-content-around mb-3">
                    <div class="col-4">
                        <label>Fecha de inicio</label>
                        <input class="form-control" type="text" readonly id="fechaInicioDetalle">
                    </div>
                    <div class="col-4">
                        <label>Fecha de finalizacion</label>
                        <input class="form-control" type="text" readonly id="fechaFinDetalle">
                    </div>
                    <div class="col-4">
                        <label>Estado de tarea</label>
                        <input class="form-control" type="text" readonly id="estadoTareaDetalle">
                    </div>
                </div>
                <div class="row form-group justify-content-around mb-3">
                    <div class="col-12">
                        <label>Descripcion de la tarea</label>
                        <textarea class="form-control" type="text" rows="4" readonly id="descripcionTareaDetalle"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12" id="comentariosTareaTotales">
                        <div class="row mb-3">
                            <div class="col-3">
                                Nombre Usuario
                            </div>
                            <div class="col-9">
                                Comentario realizado por un usuario
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-3">
                                Nombre Usuario
                            </div>
                            <div class="col-9">
                                Comentario realizado por un usuario
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-3">
                                Nombre Usuario
                            </div>
                            <div class="col-9">
                                Comentario realizado por un usuario
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row form-group justify-content-center">
                    <div class="col-10">
                        <input class="form-control" type="text" id="comentarioUsuario">
                    </div>
                    <div class="col-2">
                        <button class="btn btn-info" onclick="enviarComentario()">Comentar</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="eliminarInfo()" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

django_tareas/templates/ingresoUsuario.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Vista de ingreso</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="bg-light position-absolute start-50 top-50 translate-middle" style="height: 700px; width: 600px;">
            <div class="bg-light position-absolute start-50 top-50 translate-middle text-center" style="width: 300px; height: 550px;">
                <form method="post" action="{% url 'django_tareas:index' %}">
                    {% csrf_token %}
                    <img src="{% static 'logoApp.png' %}" width="100px" class="mb-3">
                    <div class="form-group mb-3">
                        <label>
                            Ingrese su nombre de usuario
                        </label>
                        <input class="form-control" type="text" name="nombreUsuario" placeholder="Username">
                    </div>
                    <div class="form-group mb-3">
                        <label>
                            Ingrese su password
                        </label>
                        <input class="form-control" type="password" name="contraUsuario" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary mb-3"><i class="fa-solid fa-right-to-bracket"></i> Ingresar</button>
                    <img src="{% static 'logoPUCP.png' %}" width="300px">
                </form>
            </div>
        </div>
    </body>
</html>

django_tareas/templates/iterarReact.html
<!DOCTYPE html>
<html>
    <head>
        <title>React</title>

        <!--Importacion de los componentes de react-->
        <script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

        <style>
            .nombreTexto {
                text-align: center;
                color: blue;
            }
        </style>
    </head>
    <body>
        <div id='app'></div>
        <script type="text/babel">
            function ComponenteIterar()
            {
                const [state,setState] = React.useState({
                    usuarios:[],
                    nuevoUsuario:''
                })

                function addUser()
                {
                    setState({
                        usuarios:[...state.usuarios,state.nuevoUsuario],
                        nuevoUsuario:''
                    })
                }

                function actualizarNuevoUsuario(event)
                {
                    setState({
                        ...state,
                        nuevoUsuario: event.target.value
                    })
                }

                return(
                    <div>
                        {
                            state.usuarios.map(usuario =>{
                                return(<App name={usuario}/>);
                            })
                        }
                        <button onClick={addUser}>Actualizar</button>
                        <input type='text' value={state.nuevoUsuario} onChange={actualizarNuevoUsuario} />
                    </div>
                );

            }

            function App(props)
            {
                return(
                    <h1 className="nombreTexto">Hola , {props.name}</h1>
                );
            }

            ReactDOM.render(<ComponenteIterar />,document.querySelector('#app'))
        </script>
    </body>
</html>